levels = [
    [
    'BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB',
    'B                                                                                               B',
    'B                                                                                               B',
    'B                                                                                               B',    
    'B                                                                                               B',
    'B                                                                                               B',
    'B                                                                                               B',
    'B                                                                                               B',
    'B                                                                                               B',
    'B                                                                                               B',
    'B                                                                                               B',
    'B                                                                                               B',
    'B                                                                                               B',
    'B                                                                                               B',  
    'B                                                                                               B',
    'B                                                                                               B',
    'B                                                           B              B                    B',    
    'B                                                                                               B',
    'B                                                                                               B',
    'B                                            P          B                         B             B',
    'B                                                           B                 B                 B',
    'B                                                               B B B B B B                     B',
    'B                                                                                               B',
    'B                                                                                               B',
    'B                                                                                               B',
    'B                                                                                               B',
    'B                                                                                               B',  
    'B                                                                                               B',
    'B                                                                                               B',
    'B                                                                                               B',    
    'B                                                                                               B',
    'B                                                                                               B',
    'B                                                                                               B',
    'B                                                                                               B',
    'B                                                                                               B',
    'B                                                                                               B',
    'B                                                                                               B',
    'B                                                                                               B',
    'B                                                                                               B',
    'B                                                                                               B',  
    'BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB',
    ],
    [
    'BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB',
    'B                                                                                               B',
    'B                                                                                               B',
    'B                                                                                               B',    
    'B                                                                                               B',
    'B                                                                                               B',
    'B                     P                                                                         B',
    'B                                                                                               B',
    'B                                                                                               B',
    'B                                                                                               B',
    'B                                                                                               B',
    'B                                                   B                                           B',
    'B                                                                                               B',
    'B                                                                                               B',  
    'B                                                                                               B',
    'B                                                                                               B',
    'B                                                                                               B',    
    'B                                                                                               B',
    'B                                                                                               B',
    'B                                                                                               B',
    'B                                                                                               B',
    'B                                                                                               B',
    'B                                                                                               B',
    'B                                                                                               B',
    'B                                                                                               B',
    'B                                                                                               B',
    'B                                                                                               B',  
    'B                                                                                               B',
    'B                                                                                               B',
    'B                                                                                               B',    
    'B                                                                                               B',
    'B                                                                                               B',
    'B                                                                                               B',
    'B                                                                                               B',
    'B                                                                                               B',
    'B                                                                                               B',
    'B                                                                                               B',
    'B                                                                                               B',
    'B                                                                                               B',
    'B                                                                                               B',  
    'BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB',
    ]
] 